# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Running UI testing"
  lane :test do
    run_tests(scheme: "NeuroIdExample")
  end
  
  
  desc "Push a new beta build to TestFlight"
  lane :beta do

    create_keychain(
    path: "./build/KeyChain-Sandbox",
    password: ENV["KEYCHAIN_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false    
    )

    api_key = app_store_connect_api_key(
    key_id: "R2263845L3",
    issuer_id: "69a6de78-cc01-47e3-e053-5b8c7c11a4d1",
    #key_filepath: File.join(Dir.pwd, "Key"),
    key_content: ENV["APP_STORE_API_KEY"],
    is_key_content_base64: true,
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
    )

  # pilot(api_key: api_key)


    increment_build_number(xcodeproj: "NeuroIdExample.xcodeproj")
    
    import_certificate(
     certificate_path: "./builds/86WM633ZCM.cer",
     keychain_path: "/Users/runner/Library/Keychains/build/KeyChain-Sandbox-db",
     keychain_password: ENV["KEYCHAIN_PASSWORD"],      
    )
    cert(
     api_key: api_key,
     keychain_password: ENV["KEYCHAIN_PASSWORD"],
     keychain_path: "/Users/runner/Library/Keychains/build/KeyChain-Sandbox-db", # the path to the keychain where your certificates are stored
    )
    
    install_provisioning_profile(path: "./builds/provisioning.mobileprovision")
    
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "NeuroIdExample.xcodeproj",
      target_filter: "NeuroIdExample", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Debug",
      target_filter: 'github',
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    disable_automatic_code_signing(path: "NeuroIdExample.xcodeproj")
    build_app(
      clean: true,
      workspace: "NeuroIdExample.xcworkspace", 
      scheme: "NeuroIdExample", 
      include_bitcode: false,
      export_method: "app-store",
      configuration: "Debug",
      export_options: {
        provisioningProfiles: { 
           "com.neuroid.sandbox" => "com.neuroid.sandbox AppStore 1653083869",
        }
      }
    )
    upload_to_testflight
    delete_keychain(keychain_path: "/Users/runner/Library/Keychains/build/KeyChain-Sandbox-db")
  end
end
