name: Github Actions for iOS NeuroID SDK Sandbox

on:
  push:
    branches:
      - main
      - master

  repository_dispatch:
        types: [on-demand-testflight]
      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
        
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: 2.7.2
        
      - name: Bundle Install
        run: bundle install
        
      - uses: actions/cache@v2
        with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
          ${{ runner.os }}-pods-
      - name: CocoaPod Install
        run: pod install
        
      - name: Run iOS Unit testing for SDK
        run: bundle exec fastlane test
      
      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.DIST_CERT_BASE64 }}
          P12_PASSWORD: ${{ secrets.APP_STORE_API_KEY }}
          KEYCHAIN_PASSWORD: ${{ secrets.DIST_CERT_BASE64 }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
      - name: Updating fastalane
      - run: bundle update fastlane
        
      - name: Upload iOS app to Testflight
        run: bundle exec fastlane beta
        env:
         APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
         KEYCHAIN_PASSWORD: ${{ secrets.DIST_CERT_BASE64 }}
         KEYCHAIN_PATH: ${{ steps.vars.outputs.KEYCHAIN_PATH }}
         
